#!/usr/bin/env tsx
import './validate-tokens';
import './validate-no-tailwind-literals';
import './validate-motion';
import './validate-rendering';
import './validate-no-any-types';
import './validate-no-ts-suppressions';
import './validate-tokens-ast';
import './validate-react-imports';
